services:
  ui:
    image: codeforacause/udruzenjeparaplegicara:ui-#{TAG_NUMBER}#
    container_name: udruzenjeparaplegicara_ui
    ports:
      - '12011:80'
    environment:
      NEXT_PUBLIC_GOOGLE_PUBLIC_KEY: '#{NEXT_PUBLIC_GOOGLE_PUBLIC_KEY}#'
      NEXT_PUBLIC_BASE_URL: 'https://api.udruzenjeparaplegicara.codeforacause.rs'
      NEXT_PUBLIC_URL: 'https://api.udruzenjeparaplegicara.codeforacause.rs/api/v1/'
    restart: always
    depends_on:
      - api

  api:
    image: codeforacause/udruzenjeparaplegicara:api-#{TAG_NUMBER}#
    container_name: udruzenjeparaplegicara_api
    ports:
      - '12010:8080'
    environment:
      DATABASE_URL: '#{DATABASE_URL}#'
      DATABASE_PASSWORD: '#{DATABASE_PASSWORD}#'
      DATABASE_USERNAME: '#{DATABASE_USERNAME}#'
      ACTIVE_PROFILE: '#{ACTIVE_PROFILE}#'
    restart: always
    depends_on:
      - mysql

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: udruzenjeparaplegicara_mysql
    expose:
      - '3306/tcp'
    environment:
      MYSQL_ROOT_PASSWORD: '#{DATABASE_PASSWORD}#'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '#{DATABASE_PASSWORD}#'
      MYSQL_USER: '#{DATABASE_USERNAME}#'
      MYSQL_PASSWORD: '#{DATABASE_PASSWORD}#'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'udruzenjeparaplegicara-mysql:/var/lib/mysql:rw'
    restart: always
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p#{DATABASE_PASSWORD}#'
      retries: 3
      timeout: 5s

volumes:
  udruzenjeparaplegicara-mysql:
