name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image api
      run: docker build --file backend/Dockerfile --tag codeforacause/udruzenjeparaplegicara:api-${{ github.run_number }} backend/.
    - name: Build the Docker image ui
      run: docker build --file frontend/Dockerfile --tag codeforacause/udruzenjeparaplegicara:ui-${{ github.run_number }} frontend/.
    - name: Pushing docker image api to CR backend
      run: docker push codeforacause/udruzenjeparaplegicara:api-${{ github.run_number }}
    - name: Pushing docker image ui to CR backend
      run: docker push codeforacause/udruzenjeparaplegicara:ui-${{ github.run_number }}
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: '["**docker-compose.yml"]'
      env:
        TAG_NUMBER: "${{ github.run_number }}"
        DATABASE_URL: "${{ secrets.DATABASE_URL }}"
        DATABASE_PASSWORD: "${{ secrets.DATABASE_PASSWORD }}"
        DATABASE_USERNAME: "${{ secrets.DATABASE_USERNAME }}"
        ACTIVE_PROFILE: "${{ secrets.ACTIVE_PROFILE }}"
        NEXT_PUBLIC_GOOGLE_PUBLIC_KEY: "${{ secrets.NEXT_PUBLIC_GOOGLE_PUBLIC_KEY }}"
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "docker-compose.yml"
        target: "./Projects/udruzenjeparaplegicara/"
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: docker compose -f ./Projects/udruzenjeparaplegicara/docker-compose.yml up -d
